### ISSUE TITLE
"Enable Audio Recording" - keeps popping up, even after clicking extension action button

### ISSUE THREAD

**Issue by roboticsbrian** [killergerbah/asbplayer#449]
When I hit the mining hotkey, the "Enable Audio Recording" popup appears, but even after clicking the asbplayer extension button, and the 

**What happens**:
1. I hit my mining hotkey
2. The "Enable Audio Recording" popup appears
![image](https://github.com/killergerbah/asbplayer/assets/47238439/b3b5badf-ae53-4735-8551-d21a15dd9e2f)
3. I click the asbplayer extension button
4. The "Audio Recording Enabled" popup appears
![image](https://github.com/killergerbah/asbplayer/assets/47238439/3a3422b2-03ba-4482-80ef-4e8b666d7af6)
5. I let the video play again, and hit mining hotkey again
6. The "Enable Audio Recording" popup _appears again_
![image](https://github.com/killergerbah/asbplayer/assets/47238439/7f9e28fd-2882-453a-9990-55021edfb30e)

This happens on Netflix, Amazon Prime, and YouTube. I used to be able to mine on all of these services, but not anymore. The last time I was able to mine a card was 2024-06-15. 

**Platform**: 
Windows 11
Chrome Version 126.0.6478.63 (Official Build) (64-bit)
Asbplayer 1.3.1

**Comment by killergerbah** [comment]
@roboticsbrian If you open the extension manager (chrome://extensions) you should see that asbplayer has logged some errors. Can you paste those logs here?

**Comment by roboticsbrian** [comment]
> @roboticsbrian If you open the extension manager (chrome://extensions) you should see that asbplayer has logged some errors. Can you paste those logs here?

The service worker console shows this:
![image](https://github.com/killergerbah/asbplayer/assets/47238439/569d8c07-f483-45b8-b20c-f7d49db8b142)
```
background.js:2 Uncaught (in promise) Error: Failed to start recording
    at Object.startWithTimeout (background.js:2:194840)
    at async Object.startWithTimeout (background.js:2:192968)
    at async Object._recordAndForward (background.js:2:200223)
    at async Object.handle (background.js:2:199367)
startWithTimeout @ background.js:2
await in startWithTimeout (async)
(anonymous) @ background.js:2
```

**Comment by roboticsbrian** [comment]
While I was on the extension page for asbplayer (chrome://extensions/?id=hkledmpjpaehamkiehglnbelcpdflcab), I saw that **Collect Errors** was turned off. Thinking I might get more informative error messages I turned it on:
![image](https://github.com/killergerbah/asbplayer/assets/47238439/bd218ab0-b9d2-4240-aacf-c7bdbb79464b)

Now that it's turned  on, asbplayer no longer prompts to enable audio recording, and I am able to mine cards.

I tried toggling the **Collect Errors** option several times, and it does seem that when it is off, the aforementioned error occurs. When **Collect Errors** is on, I can mine without issues.

**Comment by killergerbah** [comment]
That is really interesting info - thanks!

**Comment by jackcmac** [comment]
Just started getting this same issue today when using the one click workflow. Toggling `Collect errors` does not resolve it for me. I see the following errors:

<img width="682" alt="image" src="https://github.com/killergerbah/asbplayer/assets/30657263/d62b43ab-415e-4af2-adc9-4c64bb3843eb">

macOS Sonoma 14.3
Arc v1.47.1 (based on Chromium version 126.0.6478.57)
Asbplayer 1.3.2

**Comment by madisonruppert** [comment]
I'm running into this same error.

MacOS Sonoma 14.6 (23G80)
Brave [Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (arm64)]
Asbplayer v. 1.4.2

**Comment by ecsalamanc** [comment]
Same thing happening to me. 

Asbplayer [v1.6.1]

Here's error: 
<img width="673" alt="Screenshot 2024-12-10 at 10 37 23 PM" src="https://github.com/user-attachments/assets/e911897f-500c-45ef-9377-2e28d46c5896">

**Comment by JSchoreels** [comment]
Same ...

`1
2
(()=>{"use strict";var e={2565:(e,t,r)=>{var o=r(3298),n=/[\/\?<>\\:\*\|"]/g,s=/[\x00-\x1f\x80-\x9f]/g,a=/^\.+$/,i=/^(con|prn|aux|nul|com[0-9]|lpt[0-9])(\..*)?$/i,c=/[\. ]+$/;function d(e,t){if("string"!=typeof e)throw new Error("Input must be string");var r=e.replace(n,t).replace(s,t).replace(a,t).replace(i,t).replace(c,t);return o(r,255)}e.exports=function(e,t){var r=t&&t.replacement||"",o=d(e,r);return""===r?o:d(o,"")}},3298:(e,t,r)=>{var o=r(2815),n=r(2875);e.exports=o.bind(null,n)},2815:e=>{function t(e){return e>=55296&&e<=56319}function r(e){return e>=56320&&e<=57343}e.exports=function(e,o,n){if("string"!=typeof o)throw new Error("Input must be string");for(var s,a,i=o.length,c=0,d=0;d<i;d+=1){if(s=o.charCodeAt(d),a=o[d],t(s)&&r(o.charCodeAt(d+1))&&(a+=o[d+=1]),(c+=e(a))===n)return o.slice(0,d+1);if(c>n)return o.slice(0,d-a.length+1)}return o}},2875:e=>{function t(e){return e>=55296&&e<=56319}function r(e){return e>=56320&&e<=57343}e.exports=function(e){if("string"!=typeof e)throw new Error("Input must be string");for(var o=e.length,n=0,s=null,a=null,i=0;i<o;i++)r(s=e.charCodeAt(i))?null!=a&&t(a)?n+=1:n+=3:s<=127?n+=1:s>=128&&s<=2047?n+=2:s>=2048&&s<=65535&&(n+=3),a=s;return n}}},t={};function r(o){var n=t[o];if(void 0!==n)return n.exports;var s=t[o]={exports:{}};return e[o](s,s.exports,r),s.exports}r.m=e,r.u=e=>e+".js",r.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{var e;r.g.importScripts&&(e=r.g.location+"");var t=r.g.document;if(!e&&t&&(t.currentScript&&(e=t.currentScript.src),!e)){var o=t.getElementsByTagName("script");if(o.length)for(var n=o.length-1;n>-1&&!e;)e=o[n--].src}if(!e)throw new Error("Automatic publicPath is not supported in this browser");e=e.replace(/#.*$/,"").replace(/\?.*$/,"").replace(/\/[^\/]+$/,"/"),r.p=e})(),r.b=document.baseURI||self.location.href,(()=>{var e,t,o,n,s,a,i,c,d,u,l,m;function h(e){let t="";const r=new Uint8Array(e),o=r.byteLength;for(let e=0;e<o;++e)t+=String.fromCharCode(r[e]);return window.btoa(t)}(d=e||(e={}))[d.captureFailed=1]="captureFailed",d[d.fileLinkLost=2]="fileLinkLost",(c=t||(t={}))[c.drmProtected=1]="drmProtected",c[c.fileLinkLost=2]="fileLinkLost",function(e){e[e.miningCommand=1]="miningCommand",e[e.failedToAutoLoadPreferredTrack=2]="failedToAutoLoadPreferredTrack",e[e.userRequested=3]="userRequested"}(o||(o={})),function(e){e[e.none=0]="none",e[e.showAnkiDialog=1]="showAnkiDialog",e[e.updateLastCard=2]="updateLastCard",e[e.exportCard=3]="exportCard"}(n||(n={})),function(e){e[e.remember=0]="remember",e[e.play=1]="play",e[e.pause=2]="pause"}(s||(s={})),function(e){e[e.atStart=1]="atStart",e[e.atEnd=2]="atEnd"}(a||(a={})),function(e){e[e.normal=1]="normal",e[e.condensed=2]="condensed",e[e.autoPause=3]="autoPause",e[e.fastForward=4]="fastForward",e[e.repeat=5]="repeat"}(i||(i={})),r(2565),function(e){e[e.forward=0]="forward",e[e.backward=1]="backward"}(u||(u={})),function(e){e[e.noActiveTabPermission=1]="noActiveTabPermission",e[e.drmProtected=2]="drmProtected",e[e.other=3]="other"}(l||(l={})),function(e){e[e.timedAudioRecordingInProgress=1]="timedAudioRecordingInProgress",e[e.other=2]="other"}(m||(m={}));class f extends Error{}class p{static async encode(e,t){return new Promise((async(r,o)=>{var n=new FileReader;n.onload=async e=>{try{const n=new AudioContext;if(null===e.target)return void o(new Error("Could not obtain buffer to encode"));const s=await n.decodeAudioData(e.target.result),a=[];for(let e=0;e<s.numberOfChannels;++e)a.push(s.getChannelData(e));const i=t(),c=i instanceof Worker?i:await i;c.postMessage({command:"encode",audioBuffer:{channels:a,numberOfChannels:s.numberOfChannels,length:s.length,sampleRate:s.sampleRate}}),c.onmessage=e=>{r(new Blob(e.data.buffer,{type:"audio/mp3"})),c.terminate()},c.onerror=e=>{const t=e?.error??new Error("MP3 encoding failed: "+e?.message);o(t),c.terminate()}}catch(e){o(e)}},n.readAsArrayBuffer(e)}))}}const g=new class{constructor(){this.recording=!1,this.recorder=null,this.stream=null,this.blobPromise=null}startWithTimeout(e,t,r,o=!1){return new Promise((async(n,s)=>{try{if(this.recording)return console.error("Already recording, cannot start with timeout."),void s("Already recording");await this.start(e,o),r(),this.timeoutResolve=n,this.timeoutId=setTimeout((async()=>{this.timeoutId=void 0,n(await this.stop(o))}),t)}catch(e){s(e)}}))}start(e,t=!1){return new Promise(((r,o)=>{if(this.recording)o("Already recording, cannot start");else try{const o=new MediaRecorder(e),n=[];if(o.ondataavailable=e=>{n.push(e.data)},this.blobPromise=new Promise(((e,t)=>{o.onstop=t=>{e(new Blob(n))}})),o.start(),!t){const t=new AudioContext;t.createMediaStreamSource(e).connect(t.destination)}this.recorder=o,this.recording=!0,this.stream=e,r(void 0)}catch(e){o(e)}}))}async stopSafely(e=!1){if(this.recording=!1,this.recorder?.stop(),this.recorder=null,e||(this.stream?.getTracks()?.forEach((e=>e.stop())),this.stream=null),null!==this.blobPromise){const e=await this.blobPromise;this.blobPromise=null;const t=await h(await e.arrayBuffer());void 0!==this.timeoutId&&(clearTimeout(this.timeoutId),this.timeoutId=void 0,this.timeoutResolve?.(t),this.timeoutResolve=void 0)}}async stop(e=!1){if(!this.recording)throw new Error("Not recording, unable to stop");this.recording=!1,this.recorder?.stop(),this.recorder=null,e||(this.stream?.getTracks()?.forEach((e=>e.stop())),this.stream=null);const t=await this.blobPromise;this.blobPromise=null;const r=await h(await t.arrayBuffer());if(void 0!==this.timeoutId)throw clearTimeout(this.timeoutId),this.timeoutId=void 0,this.timeoutResolve?.(r),this.timeoutResolve=void 0,new f;return r}},w=async(e,t,o)=>{if(o){const t=await(await fetch("data:audio/webm;base64,"+e)).blob(),o=await p.encode(t,(()=>new Worker(new URL(r.p+r.u(265),r.b))));e=h(await o.arrayBuffer())}const n={sender:"asbplayer-offscreen-document",message:{command:"audio-base64",base64:e,requestId:t}};chrome.runtime.sendMessage(n)},b=async e=>navigator.mediaDevices.getUserMedia({audio:{mandatory:{chromeMediaSource:"tab",chromeMediaSourceId:e}}});let y;const v=e=>{let t;return t=e instanceof DOMException&&"AbortError"===e.name?l.noActiveTabPermission:l.other,{started:!1,error:{code:t,message:e.message}}};window.onload=async()=>{const e=(e,t,r)=>{if("asbplayer-extension-to-offscreen-document"===e.sender)switch(e.message.command){case"start-recording-audio-with-timeout":const t=e.message;return b(t.streamId).then((e=>g.stopSafely().then((()=>g.startWithTimeout(e,t.timeout,(()=>{r({started:!0})})))))).then((e=>w(e,t.requestId,t.encodeAsMp3))).catch((e=>{console.error(e),r(v(e))})),!0;case"start-recording-audio":const o=e.message;return y=o.requestId,b(o.streamId).then((e=>g.stopSafely().then((()=>g.start(e))))).then((()=>r({started:!0}))).catch((e=>{console.error(e),r(v(e))})),!0;case"stop-recording-audio":const n=e.message;return g.stop().then((e=>{r({stopped:!0}),w(e,y,n.encodeAsMp3)})).catch((e=>{let t;e instanceof f?t=m.timedAudioRecordingInProgress:(console.error(e),t=m.other);const o={stopped:!1,error:{code:t,message:e.message}};r(o)})),!0}};chrome.runtime.onMessage.addListener(e),window.addEventListener("beforeunload",(t=>{chrome.runtime.onMessage.removeListener(e)}))}})()})();
//# sourceMappingURL=offscreen-audio-recorder.js.map`

![CleanShot 2025-01-05 at 23 37 47](https://github.com/user-attachments/assets/803a70a8-cb0d-4c37-8402-619753f9d5d4)

**Comment by abcdef1000** [comment]
I got the same issue. Turns out i had a volume master extension that had to be turned off. Check your extensions?

**Comment by killergerbah** [comment]
Closing this since I've documented the Volume Master issue on the [docs](https://docs.asbplayer.dev/docs/common-issues)

**Comment by ViniciusTaborda** [comment]
For me it was also Volume Master!
Thanks guys!

**Comment by JSchoreels** [comment]
Never used Volume Master in my case
